version: '3.8'

services:
  bmad-method:
    build: .
    container_name: bmad-method
    ports:
      - "3333:3000"  # Using port 3333 to avoid conflicts
    volumes:
      # Mount a local workspace directory for your projects
      - ./workspace:/workspace
      # Mount the bmad-method source for development
      - ./:/app:ro
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: /bin/sh
    networks:
      - bmad-network

networks:
  bmad-network:
    driver: bridge